name: GameErauntsiaMC
version: 4.0
author: galaipa
main: io.github.galaipa.GameErauntsiaMC
depend: [Vault]
softdepend: [Multiverse-Core]
commands:
    wl:
        description: WhitelistGE pluginaren komando nagusia
        usage: /wl
        aliases: []
        permission: wl.erabili
        permission-message: Ez daukazu hori egiteko baimenik
    tutoriala:
        description: Orrialdean erregistratzeko pausoak azaldu
        usage: /tutoriala
        aliases: []
    laguntza:
        description: Administratzailei laguntza eskatzeko
        usage: /laguntza
        aliases: []
    arauak:
        description: Arau zerrenda ikusteko
        usage: /arauak
        aliases: []
    berriak:
        description: Webguneko azken berriak ikusteko
        usage: /berriak
        aliases: []
    telegram:
        description: Telegram aktibatu/desaktibatu
        usage: /telegram
        aliases: []
        permission: wl.erabili
        permission-message: Ez daukazu hori egiteko baimenik
    rss:
        description: RSS aktibatu/desaktibatu
        usage: /berriak
        aliases: []
        permission: wl.erabili
        permission-message: Ez daukazu hori egiteko baimenik
permissions:
    wl.erabili:
        default: op
    rss.broadcast:
        default: false     